Retrieving document at './wsdlfile/S1.wsdl'.
Retrieving document at './wsdlfile/M1.wsdl'.
s:http://www.w3.org/2001/XMLSchema
wsdl:http://schemas.xmlsoap.org/wsdl/
n1:http://webxml.com.cn/
n2:Yangzhili
mime:http://schemas.xmlsoap.org/wsdl/mime/
tns:www.cea.com
http:http://schemas.xmlsoap.org/wsdl/http/
tm:http://microsoft.com/wsdl/mime/textMatching/
soap12:http://schemas.xmlsoap.org/wsdl/soap12/
soap:http://schemas.xmlsoap.org/wsdl/soap/
soapenc:http://schemas.xmlsoap.org/soap/encoding/
targetNamespace:www.cea.com
<?xml version="1.0" encoding="UTF-8"?>
<wsdl:definitions targetNamespace="www.cea.com" xmlns:s="http://www.w3.org/2001/XMLSchema" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:n1="http://webxml.com.cn/" xmlns:n2="Yangzhili" xmlns:mime="http://schemas.xmlsoap.org/wsdl/mime/" xmlns:tns="www.cea.com" xmlns:http="http://schemas.xmlsoap.org/wsdl/http/" xmlns:tm="http://microsoft.com/wsdl/mime/textMatching/" xmlns:soap12="http://schemas.xmlsoap.org/wsdl/soap12/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:soapenc="http://schemas.xmlsoap.org/soap/encoding/">
  <wsdl:types>
    <s:schema elementFormDefault="qualified" targetNamespace="Yangzhili">
      <s:element name="getInfoByMobilePhone">
        <s:complexType>
          <s:sequence>
            <s:element maxOccurs="1" minOccurs="0" name="PhoneNumber" type="s:string"/>
            <s:element maxOccurs="1" minOccurs="0" name="UserId" type="s:string"/>
          </s:sequence>
        </s:complexType>
      </s:element>
      <s:element name="getInfoByMobilePhoneResponse">
        <s:complexType>
          <s:sequence>
            <s:element maxOccurs="1" minOccurs="0" name="getInfoByMobilePhoneResult" type="tns:MobilePhone"/>
          </s:sequence>
        </s:complexType>
      </s:element>
      <s:complexType name="MobilePhone">
        <s:sequence>
          <s:element maxOccurs="1" minOccurs="0" name="Mobile" type="s:string"/>
          <s:element maxOccurs="1" minOccurs="1" name="QueryResult" type="s:boolean"/>
          <s:element maxOccurs="1" minOccurs="0" name="Province" type="s:string"/>
          <s:element maxOccurs="1" minOccurs="0" name="City" type="s:string"/>
          <s:element maxOccurs="1" minOccurs="0" name="AreaCode" type="s:string"/>
          <s:element maxOccurs="1" minOccurs="0" name="PostCode" type="s:string"/>
          <s:element maxOccurs="1" minOccurs="0" name="Corp" type="s:string"/>
          <s:element maxOccurs="1" minOccurs="0" name="Card" type="s:string"/>
        </s:sequence>
      </s:complexType>
      <s:element name="MobilePhone" nillable="true" type="tns:MobilePhone"/>
    </s:schema>
    <s:schema elementFormDefault="qualified" targetNamespace="http://webxml.com.cn/">
      <s:element name="getStockInfo">
        <s:complexType>
          <s:sequence>
            <s:element maxOccurs="1" minOccurs="0" name="theStockCode" type="s:string"/>
            <s:element maxOccurs="1" minOccurs="0" name="userID" type="s:string"/>
          </s:sequence>
        </s:complexType>
      </s:element>
      <s:element name="getStockInfoResponse">
        <s:complexType>
          <s:sequence>
            <s:element maxOccurs="1" minOccurs="0" name="getStockInfoResult" type="tns:ArrayOfString"/>
          </s:sequence>
        </s:complexType>
      </s:element>
      <s:complexType name="ArrayOfString">
        <s:sequence>
          <s:element maxOccurs="unbounded" minOccurs="0" name="string" nillable="true" type="s:string"/>
        </s:sequence>
      </s:complexType>
    </s:schema>
  </wsdl:types>
  <wsdl:message name="getStockInfoSoapIn">
    <wsdl:part name="parameters" element="n1:getStockInfo">
    </wsdl:part>
  </wsdl:message>
  <wsdl:message name="getStockInfoSoapOut">
    <wsdl:part name="parameters" element="n1:getStockInfoResponse">
    </wsdl:part>
  </wsdl:message>
  <wsdl:message name="getStockInfoSoapfault">
    <wsdl:part name="parameters" element="n1:getStockInfoResponse">
    </wsdl:part>
  </wsdl:message>
  <wsdl:message name="getInfoByMobilePhoneSoapIn">
    <wsdl:part name="parameters" element="n2:getInfoByMobilePhone">
    </wsdl:part>
  </wsdl:message>
  <wsdl:message name="getInfoByMobilePhoneSoapOut">
    <wsdl:part name="parameters" element="n2:getInfoByMobilePhoneResponse">
    </wsdl:part>
  </wsdl:message>
  <wsdl:portType name="SMServiceSoap">
    <wsdl:operation name="getInfoByMobilePhone">
      <wsdl:input message="tns:getInfoByMobilePhoneSoapIn">
    </wsdl:input>
      <wsdl:output message="tns:getInfoByMobilePhoneSoapOut">
    </wsdl:output>
    </wsdl:operation>
    <wsdl:operation name="getStockInfo">
      <wsdl:input message="tns:getStockInfoSoapIn">
    </wsdl:input>
      <wsdl:output message="tns:getStockInfoSoapOut">
    </wsdl:output>
      <wsdl:fault message="tns:getStockInfoSoapfault">
    </wsdl:fault>
    </wsdl:operation>
  </wsdl:portType>
  <wsdl:binding name="SMServiceSoap" type="tns:SMServiceSoap">
    <soap:binding transport="http://schemas.xmlsoap.org/soap/http"/>
    <wsdl:operation name="getInfoByMobilePhone">
      <soap:operation soapAction="Yangzhili/getInfoByMobilePhone" style="document"/>
      <wsdl:input>
        <soap:body use="literal"/>
      </wsdl:input>
      <wsdl:output>
        <soap:body use="literal"/>
      </wsdl:output>
    </wsdl:operation>
    <wsdl:operation name="getStockInfo">
      <soap:operation soapAction="http://webxml.com.cn/getStockInfo" style="document"/>
      <wsdl:input>
        <soap:body use="literal"/>
      </wsdl:input>
      <wsdl:output>
        <soap:body use="literal"/>
      </wsdl:output>
      <wsdl:fault>
        <soap:fault use="literal"/>
      </wsdl:fault>
    </wsdl:operation>
  </wsdl:binding>
  <wsdl:service name="SMService">
    <wsdl:port name="SMServiceSoap" binding="tns:SMServiceSoap">
      <soap:address location="http://webservice.36wu.com/MobilePhoneService.asmx"/>
    </wsdl:port>
  </wsdl:service>
</wsdl:definitions>
