<?xml version='1.0' encoding='UTF-8'?><wsdl:definitions xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:tns="http://impl.sysdata.provider.service.ceair.com/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:ns2="http://schemas.xmlsoap.org/soap/http" xmlns:ns1="http://sysdata.provider.service.ceair.com/" name="CargosWServiceImplService" targetNamespace="http://impl.sysdata.provider.service.ceair.com/">
    <wsdl:import location=".\cargos-WService-soap.wsdl" namespace="http://sysdata.provider.service.ceair.com/"/>
    <wsdl:binding name="CargosWServiceImplServiceSoapBinding" type="ns1:CargosWService">
        <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
        <wsdl:operation name="queryData">
            <soap:operation soapAction="" style="document"/>
            <wsdl:input name="queryData">
                <soap:body use="literal"/>
            </wsdl:input>
            <wsdl:output name="queryDataResponse">
                <soap:body use="literal"/>
            </wsdl:output>
        </wsdl:operation>
    </wsdl:binding>
    <wsdl:service name="CargosWServiceImplService">
        <wsdl:port binding="tns:CargosWServiceImplServiceSoapBinding" name="CargosWServiceImplPort">
            <soap:address location="http://eal.ceair.com:80/e-mdp/ws/cargos-WService-soap/"/>
        </wsdl:port>
    </wsdl:service>
</wsdl:definitions>